site_name: spec2rtl
site_author: Utkarsh
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Developer:
    - Overview: developer/index.md
    - Architecture: developer/architecture.md
    - Modules: developer/modules.md
    - Prompts: developer/prompts.md
    - Knowledge Source: developer/knowledge_source.md

